patreon: TribeWarez
custom:
  - https://paypal.me/ozz303?country.x=DE&locale.x=de_DE
  - https://donate.tribewarez.com/solana
  - https://donate.tribewarez.com/nmtc
  - https://donate.tribewarez.com/pptc
