patreon: TribeWarez
custom:
  - https://www.paypal.com/donate/?business=TribeWarez
  - https://donate.tribewarez.com/solana
  - https://donate.tribewarez.com/nmtc
  - https://donate.tribewarez.com/pptc
